version: '3'
services:
  db:
    container_name: db
    image: mongo:5
    restart: always
    ports:
      - 27017:27017
    volumes:
        - ./mongo:/data/db
    environment:
        MONGO_INITDB_ROOT_USERNAME: root
        MONGO_INITDB_ROOT_PASSWORD: root
        MONGO_INITDB_DATABASE: test
